version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend-app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ec2-user

  BeforeAllowTraffic:
    - location: scripts/run_migrations.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ec2-user

