version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build phase...
      - npm run build || echo "No build script defined"

artifacts:
  files:
    - appspec.yml
    - package.json
    - backendreact.js
    - index.js
    - migrations/**/*  # Include migration files if any
    - seeds/**/*       # Include seed files if any
    - scripts/**/*  # Only if you're using hooks